### PR TITLE
added support for v2.0.0+ of mongo driver

### PR DESCRIPTION
**Pull request by himyouten**
Also added debug flag to show extra debug, e.g. error exceptions

### CODE REVIEW

**Comment by eheydrick** [comment]
Thanks for the PR! I tried the changes with the 1.12.x mongo gem it wouldn't run due to `Mongo::Logger` not being in the older version. I'm wondering if we shouldn't just drop the 1.12.x gem and move completely to 2.x?

**Comment by himyouten** [comment]
Happy to only use 2.x as I personally don't run 1.12.x but I tried to keep it backward compatible.  But tbh I didn't test it with 1.12.x.  We can wrap the Mongo::Logger calls to only trigger if the version is 2.x and up if we do want to try to be backward compatible.  If you want me to try that, I can have a go and you can test with 1.12.x

**Comment by eheydrick** [comment]
I'm ok with moving completely to 2.x and releasing a major version. 2.x is compatible with mongodb 2.4+ and we need 2.2.x to get mongodb 3.2 support anyways.

**Comment by PuKoren** [comment]
Do you plan to merge and release anytime soon?

**Comment by eheydrick** [comment]
@PuKoren yes, I'd like to merge this and cut a new release asap.
@himyouten can you address moving the plugin completely to 2.x?

**Comment by eheydrick** [comment]
Can you rebase this against master.

**Comment by himyouten** [comment]
@eheydrick I've done the rebase on my fork https://github.com/himyouten/sensu-plugins-mongodb/commits/master but not sure how to get this over to you.  Maybe because of the conflict?  Let me know if there's anything else!

**Comment by PuKoren** [comment]
Not sure why it did rebased

Done the rebase here as sample: https://github.com/sensu-plugins/sensu-plugins-mongodb/pull/21

Commands to rebase on your branch:

```
git reset --hard 6458a9edf2ea4a3f11342169167b7f34720d8b77
git remote add base git@github.com:sensu-plugins/sensu-plugins-mongodb.git
git fetch base
git rebase base/master
//fix conflicts
add .
git rebase --continue
git push -f
```

**Comment by mattyjones** [comment]
@eheydrick If this is good I will do a manual merge.

**Comment by himyouten** [comment]
@mattyjones I just rebased using @PuKoren's instructions

**Comment by mattyjones** [comment]
@himyouten I will merge this by hand later on today.

Thanks!

**Pull request merged**
