### PR TITLE
Refactored metrics collection code and added check-mongodb-metrics.rb

### PR DESCRIPTION
**Pull request by stefano-pogliani**
## Pull Request Overview
I have created this PR to introduce a check based on the same data collected by
`metrics-mongodb.rb` and implemented in ruby instead of python.

To accomplish this metrics collection has been moved into a shared `lib/` class and
refactored to (marginally) improve readability and consistency across mongo versions.

On top of the tests added for the metrics collection class, manual testing was done against
the docker images `mongo:2.4.12`, `mongo:2.6.11`, and `mongo:3.2.9`.

## Pull Request Checklist

**Is this in reference to an existing issue?** No

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [x] Tests

- [x] Add the plugin to the README

- [x] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by stefano-pogliani** [comment]
Hello,

I named the new check script `check-mongodb-metrics.rb` because `check-mongodb.rb`
was used and `check-mongo.rb` seemed too confusing to me.

My initial idea was to replace the existing `check-mongodb.rb` (dropping the python script
and the pymongo requirement) and change the version to 2.0.0 but I did not do that because
the [contribution instructions](http://sensu-plugins.io/docs/developer_guidelines.html#issue-and-pull-request-submissions) state:
```
[...] the major version should only be bumped by a core contributor.
```

Would it be fine to replace the existing script and change the major version?

**Comment by sstarcher** [comment]
@stefano-pogliani As long as your new check reimplements the old python stuff I believe it's fine to bump the major version and drop the python requirements.

**Comment by stefano-pogliani** [comment]
Hello @sstarcher,

A quick look at the python code suggests that is does more then just expose metrics and compare them against thresholds.
It is then best to keep it as-is because I would not have the time (or the ruby skills) to re-implement all the functionality.

Would simply add `check-mongodb-metrics.rb` work for you?

**Comment by sstarcher** [comment]
@stefano-pogliani sounds good to me, merged

**Comment by stefano-pogliani** [comment]
Thank you :-)

**Pull request merged**
