### PR TITLE
Added more metrics to the metrics-mongodb.rb

### PR DESCRIPTION
**Pull request by RycroftSolutions**
## Pull Request Checklist

There is no existing issue relating to this pull request - please treat as an enhancement

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by sstarcher** [comment]
failing ci

**Comment by RycroftSolutions** [comment]
Hi Shane,

Being new to this I would like to resolve the issue you mention but I’m not sure what needs to be done.

Can you clarify this a little for me please?

Best regards,
Neil

**Comment by RycroftSolutions** [comment]
Failed travis ci test so will start again with new fork

**Comment by RycroftSolutions** [comment]
Hi Shane,

I think I have resolved the issues that were highlighted by this pull request but the “def” statement issue was not something that I changed in this pull request.

Best regards,
Neil

**Comment by sstarcher** [comment]
@RycroftSolutions did you close this on purpose?

**Comment by RycroftSolutions** [comment]
Yes, I wanted to start from scratch

Has it caused a problem?

**Comment by sstarcher** [comment]
No, that is fine @RycroftSolutions let me know when you get the new one up.  In most cases you don't have to create a new fork to fix the issues.

**Comment by RycroftSolutions** [comment]
I did update the metrics-mongodb.rb and submit a new pull request which should fix the travis issues but the initial problem with the “def” statement was not committed by me.

I am still getting to grips with this as I have never contributed to the community before so I may, or may not have everything in place for the update to be merged.

Is this something you can check for me and let me know if I need to do anything else?

**Comment by sstarcher** [comment]
I don't see the pull request

**Comment by RycroftSolutions** [comment]
Ive probably got something wrong but this is the link I have

https://github.com/RycroftSolutions/sensu-plugins-mongodb/pull/1

**Comment by sstarcher** [comment]
@RycroftSolutions that's a pull request against your repo not against this one

**Comment by RycroftSolutions** [comment]
I do apologise, I will start again from scratch and hopefully get it right eventually

Thanks for helping though

**Comment by RycroftSolutions** [comment]
Hi Shane,

Is this correct now?

https://github.com/sensu-plugins/sensu-plugins-mongodb/pull/28

**Pull request closed without merging**
