### PR TITLE
Update metrics-mongodb.rb to add SSL mode

### PR DESCRIPTION
**Pull request by FlorinAndrei**
Added SSL connection options for when the DB only allows SSL.

### CODE REVIEW

**Comment by FlorinAndrei** [comment]
This exact same code passed Travis in the other repo:

https://github.com/sensu/sensu-community-plugins/pull/1094

**Comment by rmc3** [comment]
@FlorinAndrei Looks like this repository hasn't had a Gemfile added yet. I've added that now, waiting to see if the tests pass. 

Once we have passing tests, please rebase on master and your tests should be more accurate.

**Comment by mattyjones** [comment]
@FlorinAndrei 

If you rebase this should pass, sorry for the wait.

**Comment by eheydrick** [comment]
I think the tests will pass now. Would you mind updating the CHANGELOG under unreleased and we'll merge this.

**Comment by mattyjones** [comment]
@FlorinAndrei 

Do you still want to tackle this?

**Comment by eheydrick** [comment]
Closing due to age. Please rebase if this is still useful.

**Pull request closed without merging**
